trigger:
  branches:
    include:
    - '*' 
pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: terraform init ./terraform
  displayName: 'Terraform init'

- script: terraform plan ./terraform
  displayName: 'Terraform plan'