---

  - name: pull image
    shell: "docker pull livingdevops/lidop.serverspec"
    when: 
      - install_mode == "online"
      - node == "master"

  - name: tag image
    shell: "docker tag livingdevops/lidop.serverspec registry.service.lidop.local:5000/lidop/serverspec:latest"
    when: node == "master"

  - name: push image
    shell: "docker push registry.service.lidop.local:5000/lidop/serverspec:latest"
    when: node == "master"
