---

- name: Init
  block:
  - set_fact: ipaddress="{{ lookup('env','IPADDRESS') }}"
  - set_fact: public_ipaddress="{{ lookup('env','PUBLIC_IPADDRESS') }}"

  - set_fact: secret_password="{{ secret_password_generator }}"  

  - name: set base_urls to ip
    set_fact: 
      base_url: "{{ protocol }}://{{ public_ipaddress }}"
      jenkins_base_url: "{{ protocol }}://{{ public_ipaddress }}/jenkins"  
      gitbucket_base_url: "{{ protocol }}://{{ public_ipaddress }}/gitbucket"  
    when: domain_name == "lidop.local"
    
  - name: set base_urls to xip.io
    set_fact: 
      base_url: "{{ protocol }}://www.{{ public_ipaddress }}.{{ domain_name }}"  
      jenkins_base_url: "{{ protocol }}://www.{{ public_ipaddress }}.{{ domain_name }}/jenkins"  
      gitbucket_base_url: "{{ protocol }}://www.{{ public_ipaddress }}.{{ domain_name }}/gitbucket"  
    when: domain_name == "xip.io"

  - name: set base_urls to domain name
    set_fact: 
      base_url: "{{ protocol }}://{{ domain_name }}"  
      jenkins_base_url: "{{ protocol }}://{{ domain_name }}/jenkins"  
      gitbucket_base_url: "{{ protocol }}://{{ domain_name }}/gitbucket" 
    when: 
      - domain_name != "lidop.local"
      - domain_name != "xip.io"

  - name: Read swarm manager ip
    consul_kv:
        key: "config/{{ item }}"
        host: "{{ ipaddress }}"
    register: "{{ item }}"
    when: node == "worker"
    with_items:
      - swarm_manager_ip
      - swarm_manager_token
      - secret_password

  - debug:
      msg: "Public IP: {{ public_ipaddress }}"  

  - debug:
      msg: "Private IP: {{ ipaddress }}"  
 
  - debug:
      msg: "Install Mode: {{ install_mode }}"  

  - debug:
      msg: "Secret: {{ secret_password }}"  

  - debug:
      msg: "protocol: {{ protocol }}"  

  - debug:
      msg: "certificate_creation: {{ certificate_creation }}"  

  - debug:
      msg: "Node MasterIpaddress: {{ node_master_ipaddress }}"  
    when: node == "worker"

  tags: init