---

- name: install software
  import_tasks: software.yml

- name: init the System
  import_tasks: init.yml

- name: ssh configuration
  import_tasks: ssh.yml

- name: create the user
  import_tasks: user.yml

- name: copy config files
  import_tasks: config.yml

- name: enable mount
  import_tasks: mount.yml

- name: install docker
  import_tasks: docker.yml

- name: startup consul
  import_tasks: consul.yml

- name: startup registry
  import_tasks: registry.yml

- name: startup openldap
  import_tasks: openldap.yml
  when: node == "master"

- name: startup portainer
  import_tasks: portainer.yml
  when: node == "master"

- name: startup postgres
  import_tasks: postgres.yml
  when: node == "master"

- name: startup gitbucket
  import_tasks: gitbucket.yml
  when: node == "master"

- name: startup jenkins
  import_tasks: jenkins.yml
  when: node == "master"

- name: startup portal
  import_tasks: web.yml

- name: configure
  import_tasks: poststeps.yml
  when: node == "master"

- name: backup
  import_tasks: backup.yml
  when: node == "master"

- name: execute extend yml
  import_tasks: extend.yml
  when: node == "master"
