---

- name: start builds
  block:

  - name: Configure git
    shell: "git config --global user.email {{ root_user }}@lidop.local " 
  - name: Configure git
    shell: "git config --global user.name  {{ root_user }} " 

  - name: Create Repository in gitbucket
    uri:
      method: POST
      status_code: 200
      url: http://{{ ipaddress }}:8081/gitbucket/api/v3/orgs/LiDOP/repos
      user: "{{ root_user }}"
      password: "{{ root_password }}"
      force_basic_auth: yes
      body: '{ "name": "{{ item }}", "private": true }'
      body_format: json
    with_items: 
      - Jenkins.Lib
      - Environment

  - name: Checkin files for Plugins
    shell: |
      rm -r -f /tmp/work
      mkdir /tmp/work
      cd /tmp/work
      git clone "http://{{ root_user }}:{{ root_password }}@{{ ipaddress }}:8081/gitbucket/git/LiDOP/{{ item.name }}.git"
      cd {{ item.name }}
      cp -a {{ item.folder }}/** .
      git add .
      git commit -m "initial commit"
      git push --set-upstream origin master
    with_items: 
      - { name: 'Environment', folder: '/vagrant/plugins/environment' }
      - { name: 'Jenkins.Lib', folder: '/vagrant/configs/jenkins.sharedlib' }

  - name: Create Environment Builds
    uri:
      url: 'http://{{ ipaddress }}/jenkins/job/LiDOP/job/Load_Plugin/buildWithParameters?token=CreateBuilds&ProjectName=Environment&PluginUrl=http://{{ ipaddress }}:8081/gitbucket/git/LiDOP/Environment.git&Branch=*/master'
      status_code: 201
      user: "{{ root_user }}"
      password: "{{ root_password }}"
      force_basic_auth: yes
      headers:
        Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"

  # - name: Create first Backup
  #   uri:
  #     url: 'http://{{ ipaddress }}/jenkins/job/LiDOP/job/Maintenance/job/Backup/build'
  #     status_code: 201
  #     user: "{{ root_user }}"
  #     password: "{{ root_password }}"
  #     force_basic_auth: yes
  #     headers:
  #       Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"

  - name: Store swarm manager ip
    consul_kv:
        key: config/swarm_manager_ip
        host: "{{ ipaddress }}"
        value: "{{ ipaddress }}"
    when: node == "master"

  - name: read swarm worker token
    shell: sudo docker swarm join-token -q worker
    register: swarm_worker_token
    when: node == "master"

  - name: Store swarm worker token
    consul_kv:
        key: config/swarm_worker_token
        host: "{{ ipaddress }}"
        value: "{{ swarm_worker_token.stdout }}"
    when: node == "master"

  - name: read swarm manager token
    shell: sudo docker swarm join-token -q manager
    register: swarm_manager_token
    when: node == "master"

  - name: Store swarm manager token
    consul_kv:
        key: config/swarm_manager_token
        host: "{{ ipaddress }}"
        value: "{{ swarm_manager_token.stdout }}"
    when: node == "master"

  - name: Store secret_password in Consul
    consul_kv:
        key: config/secret_password
        host: "{{ ipaddress }}"
        value: "{{ secret_password }}"
    when: node == "master"

  - name: Store base_url in Consul
    consul_kv:
        key: config/base_url
        host: "{{ ipaddress }}"
        value: "{{ base_url }}"
    when: node == "master"

  - name: Store root_user in Consul
    consul_kv:
        key: config/root_user
        host: "{{ ipaddress }}"
        value: "{{ root_user }}"
    when: node == "master"

  - debug:
      msg: "Secret Password: {{ secret_password }}"

  tags: startup