---

- name: Install Software
  block:
    - name: Install required packages
      apt: 
        name: "{{ packages }}"
        update_cache: yes 
        state: present
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - jq
          - software-properties-common
          - default-jre
          - nfs-kernel-server
          - dos2unix 
      when: install_mode == "online"
  
    - name: install docker-py
      shell: pip install docker
      when: install_mode == "online"
      
    - name: install docker-py
      shell: pip install docker-compose
      when: install_mode == "online"

  tags: software