---

- name: setup LiDOP
  hosts: localhost
  become: yes

  pre_tasks:
    - include_vars: /tmp/lidop/.lidop_config.yaml
    - name: 'dos2unix vault'
      raw: dos2unix /tmp/lidop/install/vault-env 
    - name: 'chmod vault'
      raw: chmod +x /tmp/lidop/install/vault-env 

  roles:
    - { role: lidop_host_preparation }
    - { role: docker }
    - { role: lidop }
