---

- name: setup LiDOP
  hosts: localhost
  become: yes

  pre_tasks:
    - include_vars: /vagrant/.lidop_config.yaml
    - include_vars: /vagrant/.temp.yaml
      ignore_errors: yes

  roles:
    - { role: lidop }
    - { role: serverspec}
